### PR TITLE
[eclipse/xtext#1851] Add more Junit5 bundles to TP

### PR DESCRIPTION
**Pull request by szarnekow**
see eclipse/xtext#1851

### CODE REVIEW

**Comment by szarnekow** [comment]
@cdietrich what do you think?

**Comment by cdietrich** [comment]
do we need it in oomph too?

**Comment by cdietrich** [comment]
+ can you do same for xtend?

**Comment by szarnekow** [comment]
> * can you do same for xtend?

The Xtend target platform does not list anything about Junit5. Should we start doing that?

**Comment by cdietrich** [comment]
have no idea why @kthoms any idea?

**Comment by szarnekow** [comment]
> do we need it in oomph too?

Done

**Comment by szarnekow** [comment]
> have no idea why @kthoms any idea?

Technically we don't need it from Xtend since there shouldn't be real dependency. We do have `org.eclipse.xtend.core.validation.XtendValidator.junitAnnotations` as plain strings though.

**Comment by cdietrich** [comment]
Bildschirmfoto vom 2020-09-22 13-30-50

**Comment by szarnekow** [comment]
True, but we don't run through the code paths for Junit5, do we?

**Comment by cdietrich** [comment]
yes.

**Comment by cdietrich** [comment]
but do we in eclipse?

**Comment by szarnekow** [comment]
Hmm fair point. We actually don't.
Why is it in the TP?

**Comment by cdietrich** [comment]
do we have hybrid base classes with `@beforeeach`  somewhere?

**Comment by szarnekow** [comment]
Indeed we do. I was looking for `@Test` usages ... but the BeforeEach lead to the right track.

**Review by kthoms — APPROVED** [review]
I'm fine with those additions.

**Comment by cdietrich** [comment]
so shoudl we simply add it to xtend too to be on the safe side?

**Comment by szarnekow** [comment]
> so shoudl we simply add it to xtend too to be on the safe side?

Yes. It'll also help to avoid exactly the confusion that we currently have.

**Review by cdietrich — APPROVED** [review]

**Pull request merged**
