### PR TITLE
[#1361] Add missing "@since 2.22" tag.

### PR DESCRIPTION
**Pull request by miklossy**
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
am not sure if i consider this api
@szarnekow what do you think?

**Comment by miklossy** [comment]
The API-Diff report recognizes this as added API.

**Comment by cdietrich** [comment]
ping @szarnekow

**Comment by szarnekow** [comment]
Even though it's not API, a since tag documents when something was introduced. For this particular case, I'm fine with leaving this out.

**Pull request closed without merging**
