### PR TITLE
[#780] proper fix for profiles in submodules

### PR DESCRIPTION
**Pull request by cdietrich**
[#780] proper fix for profiles in submodules
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
@kittaakos could you give my branch a try

**Comment by kittaakos** [comment]
> @kittaakos could you give my branch a try

Sure. (I assume, `mvn clean verify` should be sufficient.)

**Comment by cdietrich** [comment]
Yes. With a -Dmaven.repo.local=~/tmp/some/temp/dir

**Comment by kittaakos** [comment]
Yes, it works nicely. The build is still running (too many tests :)) but the problematic `org.eclipse.xtext.ui.codemining` dependency is there.

```
$ mkdir tmp && cd tmp && git clone https://github.com/eclipse/xtext-eclipse.git && cd xtext-eclipse && git checkout origin/cd_issue780 -b cd_issue780 && mvn clean verify -Dmaven.repo.local=~/Desktop/maven-trash/
Cloning into 'xtext-eclipse'...
remote: Counting objects: 161163, done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 161163 (delta 53), reused 157 (delta 28), pack-reused 160962
Receiving objects: 100% (161163/161163), 41.30 MiB | 2.09 MiB/s, done.
Resolving deltas: 100% (88746/88746), done.
Checking out files: 100% (6688/6688), done.
Branch 'cd_issue780' set up to track remote branch 'cd_issue780' from 'origin'.
Switched to a new branch 'cd_issue780'
[INFO] Scanning for projects...
...
[INFO] ------------------------------------------------------------------------
[INFO] Building org.eclipse.xtext.ui.codemining 2.15.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ org.eclipse.xtext.ui.codemining ---
[INFO] 
[INFO] --- tycho-packaging-plugin:1.2.0:build-qualifier (default-build-qualifier) @ org.eclipse.xtext.ui.codemining ---
[INFO] The project's OSGi version is 2.15.0.v20180808-1232
[INFO] 
[INFO] --- tycho-packaging-plugin:1.2.0:validate-id (default-validate-id) @ org.eclipse.xtext.ui.codemining ---
[INFO] 
[INFO] --- tycho-packaging-plugin:1.2.0:validate-version (default-validate-version) @ org.eclipse.xtext.ui.codemining ---
[INFO] 
[INFO] --- xtend-maven-plugin:2.14.0:compile (default) @ org.eclipse.xtext.ui.codemining ---
...

```

**Comment by kittaakos** [comment]
I ended up with a few test failures, but this is unrelated to the original issue:
```

Results :

Failed tests: 
  DirtyStateEditorSupportIntegrationTest.testSaveAndEdit:99->pushKey:172->Assert.fail:88 Document didn't change on keystroke
  DirtyStateEditorSupportIntegrationTest.testUndoRedo:118->pushKey:172->Assert.fail:88 Document didn't change on keystroke
  AnnotationWithQuickFixesHoverTest.testAnnotations:93->Assert.assertNotNull:722->Assert.assertNotNull:712->Assert.assertTrue:41->Assert.fail:86
  LinkWithEditorTest.testTextToTree:96->AbstractOutlineWorkbenchTest.assertSelected:126->Assert.assertEquals:631->Assert.assertEquals:645->Assert.failNotEquals:834->Assert.fail:88 expected:<1> but was:<0>

Tests run: 1652, Failures: 4, Errors: 0, Skipped: 19
```

Thank you for the quick fix!

**Comment by cdietrich** [comment]
the dirty one is already known and reported. the other ones i have never seen on ci.

**Comment by cdietrich** [comment]
@kthoms still waiting for your review

**Comment by szarnekow** [comment]
Ping @kthoms

**Pull request merged**
