### PR TITLE
Make loading of Xtext index better hookable

### PR DESCRIPTION
**Pull request by cdietrich**
Make loading of Xtext index better hookable

### CODE REVIEW

**Comment by cdietrich** [comment]
@szarnekow why do you think? bad idea?

**Comment by szarnekow** [comment]
> @szarnekow why do you think? bad idea?

Hmm I understand that the persister itself is not easily customizable?

**Comment by cdietrich** [comment]
we want to basically hook into the loading so that we can transform the index content into a map in the builderstatate subclass
with the load itself we have to basically copy&paste all the isloaded stuff etc

**Comment by szarnekow** [comment]
Makes sense.

**Review by szarnekow — APPROVED** [review]

**Pull request merged**
