### PR TITLE
[#1228] Statemachine example: Regenerate the Messages.java class.

### PR DESCRIPTION
**Pull request by miklossy**
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
i dont have any changes locally. is the a generate once then update manually resource?

**Comment by cdietrich** [comment]
even if i delete it i dont get any comment

**Comment by cdietrich** [comment]
i also have the feeling that the n:1 generation does not really work with incremental builds

**Comment by miklossy** [comment]
I deleted the `Messages.java` file and executed a `Project -> Clean...` After that the Messages.java file has been generated with the copyright header.
screencast

**Comment by cdietrich** [comment]
for me not. i wonder what the active annotation does and which file it picks to read the header in my and in your case

**Comment by cdietrich** [comment]
hmm now i am getting it.

**Pull request merged**
