### PR TITLE
Updated Examples

### PR DESCRIPTION
**Pull request by kthoms**
Rerun the workflows from the example projects. The following changes are produced by the current Xtext generator against a Luna target.

Additionally removed plugin.xml_gen files from the examples and added them to .gitignore per example.

### CODE REVIEW

**Comment by kthoms** [comment]
You mean .xtextbin from homeautomation? It was in the repo before, same for other .xtextbin files. Or, where did you spot .xtendbin files in the repo?

**Comment by LorenzoBettini** [comment]
I thought that .xtendbin would be not in the git repo...

**Comment by kthoms** [comment]
.xtextbin or .xtendbin?

**Comment by LorenzoBettini** [comment]
sorry... I thought I'd seen .xtendbin... I could use some rest ;)

**Comment by kthoms** [comment]
@LorenzoBettini OK then?

**Comment by LorenzoBettini** [comment]
@kthoms I recently merged this PR https://github.com/eclipse/xtext-eclipse/pull/165 into branch release_2.11.0 (not into master, I think it will be merged later). Since my PR involves a few changes into the Domainmodel example as well, I guess it will conflict with your PR. By the way, why didn't you merge into release_2.11.0?

**Pull request merged**
