### PR TITLE
[#677] Fix problem with unpacking of type

### PR DESCRIPTION
**Pull request by holgerschill**

### CODE REVIEW

**Comment by cdietrich** [comment]
wonder if you can create a branch on xtext-xtend too and run ./adjustPipelines in umbrella 
(or change the target file in xtend manually to use eclipse from your branch)

**Comment by cdietrich** [comment]
wonder if you can create a branch on xtext-xtend too and run ./adjustPipelines in umbrella 
(or change the target file in xtend manually to use eclipse from your branch)

**Comment by holgerschill** [comment]
https://ci.eclipse.org/xtext/job/xtext-xtend/job/hs_issue677_fix/

**Comment by holgerschill** [comment]
Build succeeded. Good to merge?

**Pull request merged**
