### PR TITLE
Kth/issue92

### PR DESCRIPTION
**Pull request by kthoms**

### CODE REVIEW

**Comment by kthoms** [comment]
Requires PR eclipse/xtext-extras#58 to be merged first.

**Comment by cdietrich** [comment]
@kthoms this pr is obsolete, correct?

**Comment by cdietrich** [comment]
@kthoms this is obsolete correct?

**Comment by cdietrich** [comment]
will redo this with https://github.com/eclipse/xtext-extras/issues/175

**Pull request closed without merging**
