### PR TITLE
fixed compatibility issues with eclipse oxygen 1a / photon #393

### PR DESCRIPTION
**Pull request by cdietrich**
fixed compatibility issues with eclipse oxygen 1a / photon #393

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
please review. if you prefer a reflective solution i can create a pr for that as well

**Comment by cdietrich** [comment]
am not sure how to test that. how to have secondary types in eclipse

**Comment by cdietrich** [comment]
@svenefftinge no i think we can throw away the code completely and do

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-eclipse/compare/cd_issue393c

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-eclipse/pull/396

**Comment by svenefftinge** [comment]
But the comment somehow seems alarming. If the `resolveClasspath` is done too eagerly and early it might harm. Did you check with @szarnekow why he did it?

**Comment by cdietrich** [comment]
one reason was the jdk version thingythat is fixed in Luna SR2. for the others i dont know

**Comment by svenefftinge** [comment]
Ok, so the current code avoids opening jars at all, while the change in #396 would do. The comment mentions the jdk version, so if that was fixed we might indeed go with removing all that code. I assume that the classpath gets resolved anyhow and since that information is cached, it might not be harmful to do it. OTOH it could be that we call this stuff before JDT does and maybe even worse in the UI thread.
I think this one is less-risky, but the other proposal better in the long run. I'm going with #396. If it is too bad we can restore this code.

**Comment by cdietrich** [comment]
i am still doing some measurements regarding performance.

**Comment by cdietrich** [comment]
i see a performance drop 1:55->2:05 with the getAllPackageFragmenteRoots solution.

**Comment by cdietrich** [comment]
bildschirmfoto 2017-10-04 um 09 58 51
bildschirmfoto 2017-10-04 um 09 58 27

**Comment by cdietrich** [comment]
so i propose to stick with this PR

**Comment by cdietrich** [comment]
a reflective solution for PatchedFileSystem seems no to be possible or we would even use reflection for the method signature types. but for return types? ....

**Comment by cdietrich** [comment]
replaced by https://github.com/eclipse/xtext-eclipse/pull/397

**Pull request closed without merging**
