### PR TITLE
Fixes #589: ChangeSerializerComposerTest + CompositeQuickfixTest

### LINKED ISSUE #589: Fix ChangeSerializerComposerTest + CompositeQuickfixTest
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/master/186/

cc @meysholdt

### PR DESCRIPTION
**Pull request by meysholdt**
Signed-off-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>

### CODE REVIEW

**Comment by meysholdt** [comment]
I'll merge when the build passes.

**Comment by cdietrich** [comment]
@meysholdt  it would be nice to have a review too. @JanKoehnlein @kthoms

**Comment by meysholdt** [comment]
true, but this change is needed to get the build green again.

**Comment by kthoms** [comment]
> true, but this change is needed to get the build green again.
Yes, but still someone has to review it first. Green test is good, but also there could be annotations regarding the test changes. Not assuming that you don't provide good changes, but you'll never know if something could be requested by a reviewer. Policy is to review all changes except for really trivial ones, I'm not aware that this has changed.

**Comment by meysholdt** [comment]
build is green: http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/me%252Ffix_test/

**Pull request merged**
