### PR TITLE
[#251] Remove workaround for bug#474003

### PR DESCRIPTION
**Pull request by kthoms**
The EGit IndexDiffUpdateJob interrupted Xtext builds, which made the
workaround necessary. EGit was fixed with Eclipse Mars, which is below
minimum target requirement now. This makes the workaround obsolete.

Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
i am ok with this. @szarnekow what do you think.
@kthoms we also should document the minimal egit version in the release notes

**Comment by kthoms** [comment]
I've added this to the release notes:
```
### EGit minimal version

Xtext requires to use EGit 4.1 now. We have removed a workaround that prevented an endless build loop caused by EGit [Bug#474003](https://bugs.eclipse.org/bugs/show_bug.cgi?id=474003). Since we expect that no clients are still using Xtext >= 2.20 together with the ancient EGit version, we felt safe to finally remove this workaround.
```
@szarnekow fine for you now?

**Comment by szarnekow** [comment]
Can we somehow ensure that Xtext does not run with an ancient EGit?

**Comment by kthoms** [comment]
Not really. When you try to install Xtext 2.20 you'll need at least Oxygen.3a. This is constrained. When you install EGit on top of that, you'll use either the SimRel repo or Git release repo and get a newer version. I think when you actively compose a target with Oxygen or newer, Xtext 2.20 or newer and EGit 4.0 or older, then this might be possible. I think this together is really unlikely.

**Comment by cdietrich** [comment]
i dont think we can.

**Pull request merged**
