### PR TITLE
[#1168] Minimal target platform Oxygen.3a

### PR DESCRIPTION
**Pull request by kthoms**
Update lower bound version constraints on platform related bundles with
versions from an Oxygen.3a platform.

Used an Oxygen.3a Target Platform and selected the proposed versions from it:

screenshot 247

### CODE REVIEW

**Comment by kthoms** [comment]
rebased

**Comment by cdietrich** [comment]
still would like to get a "minimal" version of this into 2.16

**Comment by szarnekow** [comment]
What is necessary to make this a mergable pr?

**Comment by kthoms** [comment]
Seems that the versions are outdated a bit. With latest Oxygen target I confirm that the mentioned versions (jdt.core, pde.ui) changed. Have to check this.

**Comment by cdietrich** [comment]
@kthoms @szarnekow anything left?

**Comment by kthoms** [comment]
Should be Ok now?

**Pull request merged**
