### PR TITLE
[366414] Made Documentation on use of Xbase more explicit

### PR DESCRIPTION
**Pull request by cdietrich**
[366414] Made Documentation on use of Xbase more explicit

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=366414

**Comment by cdietrich** [comment]
please review

**Comment by meysholdt** [comment]
👍 thx, feel free to merge

**Comment by spoenemann** [comment]
Note that the content of `org.eclipse.xtext.doc` is generated from the website, so there's no point in editing it manually.

**Comment by cdietrich** [comment]
updated docs unter xtext/maintenance

**Pull request merged**
