### PR TITLE
772: updated dmodel compiler tests

### PR DESCRIPTION
**Pull request by LorenzoBettini**
This updates compilation test expectations (https://github.com/eclipse/xtext-extras/pull/774 fixing https://github.com/eclipse/xtext-extras/issues/772).

### CODE REVIEW

**Review by cdietrich — APPROVED** [review]

**Comment by LorenzoBettini** [comment]
@cdietrich I'm waiting for the xtext-xtend master build finishes and then I'm merging this one as well

**Comment by cdietrich** [comment]
@LorenzoBettini no just merge it

**Comment by LorenzoBettini** [comment]
@cdietrich OK merged this as well.
I guess we're all set now.

**Comment by cdietrich** [comment]
yes i will start with milestone once the builds are though

**Pull request merged**
