### PR TITLE
Serialized result of document modification loses or duplicates comments

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse/xtext/issues/2487

### CODE REVIEW

**Comment by cdietrich** [comment]
@szarnekow should we mark the tests failing with `@Ignore`?

**Comment by merks** [comment]
I can force push any changes if you like...

**Comment by cdietrich** [comment]
ping @szarnekow

**Comment by szarnekow** [comment]
> ping @szarnekow

Sorry, I didn't come around looking at the case yet.

**Comment by cdietrich** [comment]
this repository has been merged/moved to https://github.com/eclipse/xtext.
please feel free to recreate this PR against that repository in case it still is relevant.

**Pull request closed without merging**
