### PR TITLE
[#1330] Add CodeMining to the Xtext Arithmetics example.

### PR DESCRIPTION
**Pull request by miklossy**
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
@miklossy will you also provide a fix for integ tests in reference projects?

**Comment by miklossy** [comment]
> 
> 
> @miklossy will you also provide a fix for integ tests in reference projects?

Yes, I can take a look at it.

**Comment by miklossy** [comment]
I rebased the PR on the master branch and resolved the conflicts resulting from the EPL-2 License update (Copyright headers).

**Comment by cdietrich** [comment]
I still don't see the additional value and also miss a fix for the integ tests

**Comment by miklossy** [comment]
@cdietrich I did some basic testing and did not find any interference with the `autoedit `functionality.
I would be really happy if we could get this through. Once this PR is merged, I will provide a PR with the necessary changes to the `xtext-reference-projects` to adapt the integration tests.

**Comment by cdietrich** [comment]
i dont care but i still dont see the addtional value.
@szarnekow @kthoms  what do you think

@miklossy i am still waiting for a corresponding pr for the reference projects

**Comment by miklossy** [comment]
I can only provide the PR on the reference-projects only after this PR has been merged. It is difficult to provide it before.

**Comment by cdietrich** [comment]
Is it? Create umbrella branch using this and use that umbrella branch in ref projects integ test Target platform

**Comment by miklossy** [comment]
Ah ok, thanks forthe hint. I will give it a try.

**Comment by miklossy** [comment]
I created the corresponding [PR](https://github.com/itemis/xtext-reference-projects/pull/115) against the integration-tests repository to prepare the `Xtext SimpleArithmetics Example` to the CodeMining support.

**Pull request merged**
