### PR TITLE
[#976] Attempt to fix occasional failures in ProblemHoverTest 

### PR DESCRIPTION
**Pull request by szarnekow**
Use TestedWorkspace instead of logic from base class to cleanup the workspace

### CODE REVIEW

**Comment by cdietrich** [comment]
needs rebase

**Comment by szarnekow** [comment]
> needs rebase

And does not work yet :(

**Comment by cdietrich** [comment]
@szarnekow did not see the test fail recently. => close this pr?

**Comment by szarnekow** [comment]
Yes, but I'll keep the branch for now.

**Pull request closed without merging**
