### PR TITLE
[eclipse/xtext-core#903] Build against 2018-12

### PR DESCRIPTION
**Pull request by cdietrich**
[eclipse/xtext-core#903] Build against 2018-12
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by kthoms** [comment]
Shall we really make this intermediate step in the example? The snapshots will have to be removed anyway for the final release.

**Comment by cdietrich** [comment]
well how else can we test against the milestones with all the equinox.ds removal the platform team did

**Comment by kthoms** [comment]
For testing this can be done manually, couldn't it? But if you prefer 2 commits here then let it be.

**Comment by cdietrich** [comment]
Can you do testing on a regular basis? I have the feeling I am the only one that does

**Pull request closed without merging**
