### PR TITLE
[J11] Update domain model to Java 11

### PR DESCRIPTION
**Pull request by cdietrich**
[J11] Update domain model to Java 11
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by kthoms** [comment]
What if the Domainmodel is installed on a machine with Java 8 only, or on a lower target?

**Comment by cdietrich** [comment]
The domain model example also won’t work on oxygen. Using 2020-06 in the target would be bogus too.
All the platform approach of moving „somehow“ to java 11 is so bad

**Review by ArneDeutsch — APPROVED** [review]
LGTM

**Comment by cdietrich** [comment]
obsolete for now

**Pull request closed without merging**
