### PR TITLE
made very flaky tests more stable. solves #31

### PR DESCRIPTION
**Pull request by cdietrich**
made very flaky tests more stable. solves #31

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by LorenzoBettini** [comment]
Just for curiosity, why is

```
Thread.sleep(10);
```

required? it's just 10 milliseconds delay... I think the important part is to wait for build, or am I missing something?

**Comment by cdietrich** [comment]
wait for build is just calling a incremental build.
i assume there is some eventing missing if the build is started too early

**Comment by LorenzoBettini** [comment]
OK... it's strange that 10 milliseconds are enough to delay the build ;)

**Pull request merged**
