### PR TITLE
[#1701] better progress reporting for queueAffectedResources

### PR DESCRIPTION
**Pull request by cdietrich**
[#1701] better progress reporting for queueAffectedResources
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

Bildschirmfoto 2021-07-19 um 14 19 36

### CODE REVIEW

**Review by miklossy — APPROVED** [review]

**Comment by cdietrich** [comment]
@szarnekow  what do you think about the change? do you have a better proposal for the message?

**Comment by szarnekow** [comment]
`Checking if abc.ext is affected`? `Checking if abc.ext must be compiled`? 
Should we have a getter for the message that can be overridden with little effort? E.g. a product based on Xtext may use a different terminology in the UI for the build.

**Comment by cdietrich** [comment]
we dont have getters for any of the messages so far.
replaced evaluating with checking

**Comment by cdietrich** [comment]
please feels free to change if you see a better message here

**Pull request merged**
