### PR TITLE
[eclipse/xtext-core#822] Use 2018-09 in Target Platform

### PR DESCRIPTION
**Pull request by cdietrich**
[eclipse/xtext-core#822] Use 2018-09 in Target Platform
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
will wait for M3 to test if that fixes the original issue

**Comment by kthoms** [comment]
Should we remove the "-photon" suffix from the file names? In the past there were different target files (photon/oxygen).

**Comment by cdietrich** [comment]
yes but i first want to get this running functionally

**Comment by kthoms** [comment]
Please resolve the conflict

**Comment by cdietrich** [comment]
replaced by https://github.com/eclipse/xtext-eclipse/pull/803

**Pull request closed without merging**
