### PR TITLE
[#1447] Provide ui test infrastructure for testing multi quickfixes

### PR DESCRIPTION
**Pull request by drkstr101**
Step 1 - AbstractMultiQuickfixTest was moved from `ui.tests` package to the `ui.testing` package, so it may be exported and used to implement other multi-quickfix tests.

Signed-off-by: Aaron R Miller <aaron.miller@waweb.io>

### CODE REVIEW

**Comment by miklossy** [comment]
Could you please add the `@since 2.23` tag and the `@Beta` annotation to the relocated AbstractMultiQuickfixTest class? Similar how it is done in the [AbstractFoldingTest](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractFoldingTest.java) class.

**Comment by drkstr101** [comment]
@miklossy Done.

**Comment by miklossy** [comment]
Thanks @drkstr101 ! I will merge this PR as soon as Xtext 2.22 has been released (maybe at the end of next week).

**Comment by drkstr101** [comment]
Awesome, good deal! =)

**Comment by miklossy** [comment]
@cdietrich Is the repository already prepared to accept PRs that are planned for 2.23 ?

**Comment by kthoms** [comment]
Yes, the release is tagged, so master is open again for changes. @miklossy you can merge.

**Comment by miklossy** [comment]
Thanks you @kthoms for clarification.

**Pull request merged**
