### PR TITLE
moved code to JavaVersion

### PR DESCRIPTION
**Pull request by cdietrich**
moved code to JavaVersion
https://github.com/eclipse/xtext/issues/2578

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Review by kthoms — CHANGES_REQUESTED** [review]
Refactor usage also:
org.eclipse.xtext.xbase.ui.builder.XbaseBuilderConfigurationBlock.updateVersionCombo()

**Comment by cdietrich** [comment]
@kthoms updated

**Comment by kthoms** [comment]
I do not see a change of XbaseBuilderConfigurationBlock in the commit

**Comment by cdietrich** [comment]
what needs to be changed?

**Review by kthoms — APPROVED** [review]
Sorry, my fault. At the time of my review the fromCompilerSourceLevel was supposed to be deprecated, which was reverted now.

**Pull request merged**
