### PR TITLE
[eclipse/xtext-eclipse#1561]:Added getter for resource variable

### PR DESCRIPTION
**Pull request by srinivasiyermv**
This getter avoids large scale  copy and paste of the class

Signed-off-by: Srinivas Iyer <srinivasiyermv@gmail.com>

### CODE REVIEW

**Comment by srinivasiyermv** [comment]
Added neccessary getter to make XtextTemplateStore extendible and avoid  copy & paste of whole class for adding additional enhancements.

**Comment by cdietrich** [comment]
@srinivasiyermv any reason why you closed this PR?

**Comment by srinivasiyermv** [comment]
@cdietrich It was by mistake

**Review by cdietrich — APPROVED** [review]

**Comment by cdietrich** [comment]
thx @srinivasiyermv

**Pull request merged**
