### PR TITLE
Also consider the listener job to be a manual build job

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by cdietrich** [comment]
TODO restart build as soon as server is usable again.
test failure does not seem to be related

**Comment by szarnekow** [comment]
Build was green. Merging.

**Comment by szarnekow** [comment]
Test failures can be reproduced locally with test suite that mimics the order of test classes on the server. Investigating before merge.

**Comment by szarnekow** [comment]
org.eclipse.xtext.ui.tests.core.resource.Storage2UriMapperTest does not remove the project that it creates.

**Pull request merged**
