### PR TITLE
[486001] Converted Proposal Provider Example Code in Docs to Xtend

### PR DESCRIPTION
**Pull request by cdietrich**
[486001] Converted Proposal Provider Example Code in Docs to Xtend

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=486001

**Comment by cdietrich** [comment]
please review

**Comment by svenefftinge** [comment]
+1

**Comment by cdietrich** [comment]
updated docs unter xtext/maintenance

**Pull request merged**
