### PR TITLE
typo in refactoring warning

### PR DESCRIPTION
**Pull request by Bananeweizen**

### CODE REVIEW

**Comment by svenefftinge** [comment]
Hi Michael, I know it seems a bit overkill for this to require a CLA, but I guess you have already, no?

**Comment by kthoms** [comment]
One issue is that if he has edited the text through the web interface, the IP validation fails, even if a CLA is signed and the Eclipse profile is associated with the GitHub profile. I have the same problem. I raised this once to Eclipse Bugzilla and played ping-pong with Eclipse and GitHub, and finally gave up.

**Comment by kthoms** [comment]
For the reference: https://bugs.eclipse.org/bugs/show_bug.cgi?id=498340

**Comment by Bananeweizen** [comment]
Sorry for the confusion. Karsten was of course right in me using the web editor. I've recreated the change locally and created a new PR.

**Pull request closed without merging**
