### PR TITLE
[497070] fixed conflicting key bindings. fixed binding on mac (cmd+alt+h is reserved)

### PR DESCRIPTION
**Pull request by cdietrich**
[497070] fixed conflicting key bindings. fixed binding on mac (cmd+alt+h is reserved)

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=497070

**Comment by cdietrich** [comment]
please review

**Review by kthoms — APPROVED** [review]

**Comment by spoenemann** [comment]
How does this change relate to eclipse/xtext#2400?

**Comment by cdietrich** [comment]
well it affects the same keybinding, but eclipse/xtext#2400 is about normal editor vs embedded editor, this is about xtext grammar editor vs xbase editors

**Pull request merged**
