### PR TITLE
fixed warnings after switch to oxygen as minimal target

### PR DESCRIPTION
**Pull request by cdietrich**
fixed warnings after switch to oxygen as minimal target
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
why will this break luna?

**Comment by kthoms** [comment]
Because you make now use of the generics (`<T> T getAdapter(Class<T> adapter)`) that have been introduced after Luna.

**Comment by szarnekow** [comment]
> This will definitely break on Luna.
Do you talk about binary incompatibility? I assume the Java compiler produces bridge methods for the generified methods.

**Comment by szarnekow** [comment]
From my understanding we did not change the code to be source compatible to the older TP. Otherwise we could not have built our stuff. Am I mistaken?

**Comment by cdietrich** [comment]
yes but afaik the code should still work. (see the code snippet i sent you via chat)
but i am ok with setting the minmal version

**Comment by szarnekow** [comment]
So am I. It will definitely not do any harm in the effort to keep the deps straight.

**Comment by kthoms** [comment]
PRs for that are on the way, e.g. https://github.com/eclipse/xtext-eclipse/pull/745

**Comment by cdietrich** [comment]
@szarnekow @kthoms ok to merge?

**Pull request merged**
