### PR TITLE
Fix for https://github.com/eclipse/xtext-eclipse/issues/209

### PR DESCRIPTION
**Pull request by sprigogin**
This change adds timestamp tracking for files outside workspace opened
in Xtext-based editors.

### CODE REVIEW

**Comment by cdietrich** [comment]
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/sprigogin_master/4/

**Comment by svenefftinge** [comment]
Thank you!

**Comment by cdietrich** [comment]
this does not work with luna, => build is broken
i can try to do an incanceof adaptable but i dont know if this will fix your actual problem

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-eclipse/pull/218/

**Comment by sprigogin** [comment]
Replacing Adapters.adapt with IAdaptable.adapt will not work with objects that can be adapted only by using adapter factories. It makes sense to change it back to Adapters.adapt as soon as Luna support is no longer required.

**Comment by cdietrich** [comment]
that was clear, i was just asking if this solves YOUR usecase ;D

**Comment by sprigogin** [comment]
IAdaptable.adapt is sufficient for my use case because FileStoreEditorInput implements IAdaptable.

**Pull request merged**
