### PR TITLE
[#501] [restructure] Move examples to sub directories

### PR DESCRIPTION
**Pull request by kthoms**
- Each example DSL is moved to a subfolder of the 'projects' folder
- Adjusted build.xml script to zip the projects from a subdir
- Additionally excluded /target and plugin.xml_gen from zip
- Changed packaging of example projects to Maven 'package' phase

Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
can you spliot this up on multiple commits that split the move and the package/wizard stuff

**Comment by kthoms** [comment]
Done

**Comment by cdietrich** [comment]
i am still not sure why this is needed. any hints?

**Comment by kthoms** [comment]
This organizes the projects in a folder per DSL:
```
/projects
   |
   +- arithmethics
   |  |
   |  +- org.eclipse.xtext.example.arithmetics
   |  +- org.eclipse.xtext.example.arithmetics.ide
   |  +- org.eclipse.xtext.example.arithmetics.tests
   |  +- org.eclipse.xtext.example.arithmetics.ui
   |  +- org.eclipse.xtext.example.arithmetics.ui.tests
   |
   +- domainmodel
   |  |
   |  +- org.eclipse.xtext.example.domainmodel
   ...
```

Not strictly technically necessary to enable the builds, just better structured.

**Comment by cdietrich** [comment]
well which structure are you planning for maven?

**Comment by cdietrich** [comment]
(i just want to make sure it works in the "endausbaustufe" which i cannot see/test right now)

**Comment by kthoms** [comment]
Build will require additional projects. This will be done in further PR.

**Pull request merged**
