### PR TITLE
[#1132] marked workbench as nullable

### PR DESCRIPTION
**Pull request by cdietrich**
[#1132] marked workbench as nullable
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by kthoms** [comment]
Sorry for asking: What's the difference between optional injections with and without that annotation?
When should optional injections annotated additionally with Nullable? I found only 3 usages of Nullable yet, but many optional Injects.

**Comment by cdietrich** [comment]
guice does not like optional only it needs to be nullable too. we already had this at different places. https://stackoverflow.com/questions/4887196/guice-nullable-annotation

**Comment by kthoms** [comment]
Thanks for clarifying. Are there other places where Nullable would make sense then, or do we change only when we hit such places like here?

**Comment by cdietrich** [comment]
in the past we fixed only places we hit

**Pull request merged**
