### PR TITLE
[#909] Optimize useage of org.eclipse.xtext.common.types.shared depend.

### PR DESCRIPTION
**Pull request by miklossy**
- Add the org.eclipse.xtext.common.types.shared dependency to the
org.eclipse.xtext.xbase.ui plugin.
- Remove that dependency from the Xtext Examples, since now it is
implicitly there.

Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
lets wait for a build. will schedule once jam is resolved

**Comment by miklossy** [comment]
@cdietrich As far as I can see, the build is green, so the PR is ready to be merged, isn't it?

**Comment by cdietrich** [comment]
looks ok for me

**Comment by cdietrich** [comment]
thanks @miklossy

**Comment by cdietrich** [comment]
could be https://github.com/eclipse/xtext-eclipse/pull/963/files

**Pull request merged**
