### PR TITLE
[eclipse/xtext-xtend#395] Try With Resources

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by szarnekow** [comment]
@epoell This should be it, right?

**Comment by szarnekow** [comment]
I merged this one into branch ep_issue397 to include it in pr #1038

**Comment by szarnekow** [comment]
I merged this one into branch ep_issue397 to include it in PR #1057

**Comment by cdietrich** [comment]
@szarnekow can this one be closed?

**Pull request closed without merging**
