### PR TITLE
X2J: Migrate the remaining Xtend code from the "org.eclipse.xtext.ui.testing" project to Java

### PR DESCRIPTION
**Pull request by nbhusare**
- [x] Migrated remaining Xtend code to Java
- [x] Ran the Maven/Gradle build locally
- [x] Adapted .classpath, build.properties, and Manifest files

Signed-off-by: nbhusare <neerajbhusare@gmail.com>

### CODE REVIEW

**Comment by miklossy** [comment]
There are some failing tests under the Domainmodel Quickfix test cases.

**Comment by cdietrich** [comment]
please note: build is currently failing due orbit changes.
these will be fixed with the asm changes i am currently working on.
i will ping you when you can rebase.

**Comment by cdietrich** [comment]
something like 

```
	public void testQuickfixesOn(CharSequence content, String issueCode, AbstractQuickfixTest.Quickfix... quickfixes) {
		IFile dslFile = dslFile(getProjectName(), getFileName(), getFileExtension(), content);
		this.project = dslFile.getProject();
		quickfixesAreOffered(openInEditor(dslFile), issueCode, quickfixes);
	}
``` solves the problem

**Comment by nbhusare** [comment]
@cdietrich @miklossy I am facing problems while correcting the history of this branch, which is why I am closing this branch. I have ported the changes, and the fix recommended by @cdietrich in the new branch https://github.com/eclipse/xtext-eclipse/pull/1418

**Pull request closed without merging**
