### PR TITLE
[456114][#229] Xtext nature overlay with the projectNatureImages extension point

### PR DESCRIPTION
**Pull request by cdietrich**
[456114][#229] Xtext nature overlay with the projectNatureImages extension point

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=456114

**Comment by cdietrich** [comment]
please review. do we really want to do this?

**Comment by cdietrich** [comment]
downside is: add xtext nature action adds the nature at the end. so the xtext overlay wont be visible by default

**Comment by svenefftinge** [comment]
+1 
Xtext really is just a framework used to build actual language plugins, so it should not expose itself into the UI too much (if at all).

**Pull request merged**
