### PR TITLE
[#1044] AbstractHyperlink: Usage of IRegion instead of Region.

### PR DESCRIPTION
**Pull request by miklossy**
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
nothing on github,
but there are also customizations in xbase.ui and usages in domainmodel. am not sure if compatibe

**Comment by miklossy** [comment]
@cdietrich Thanks for checking that! The usages in the xbase.ui and in the domainmodel are compatible with the change, otherwise there would be some compile errors.

**Comment by cdietrich** [comment]
Domainnodel is not part of the build

**Comment by miklossy** [comment]
Ah ok, you are right. I checked that again and the [DomainmodelHyperlinkHelper](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/navigation/DomainmodelHyperlinkHelper.java#L72) invokes the setHyperlinkRegion method with a Region parameter. The PR changes that parameter from Region to IRegion, and since Since all Region objects are instances of IRegion, it remains compatible.

**Comment by szarnekow** [comment]
@cdietrich Are we aiming at source compatibility or binary compatibility?

**Comment by cdietrich** [comment]
we aim to both. but as always it is a matter of compromise

**Comment by szarnekow** [comment]
I'd keep `setHyperlinkRegion(Region)` and deprecate it.

**Comment by miklossy** [comment]
@szarnekow Good idea! I updated the PR as requested.

**Pull request merged**
