### PR TITLE
Fixed typo in PersistentDataAwareDirtyResource

### PR DESCRIPTION
**Pull request by tivervac**
You can just close this ticket if you don't think it's worth deprecating these methods for the typo. Whatever the response, I'll keep it in mind for future contributions.

### CODE REVIEW

**Comment by cdietrich** [comment]
PersistentDataAwareDirtyResource is non api.
=> i am not sure if we simply should correct the typo. that do you think @szarnekow

**Comment by szarnekow** [comment]
I did not find any callers on Github. So it's likely safe to rename the method.

**Comment by cdietrich** [comment]
@tivervac could you change the pr accordingly

**Comment by cdietrich** [comment]
many thanks @tivervac

**Pull request merged**
