### PR TITLE
Use tryReadOnly instead of readOnly

### PR DESCRIPTION
**Pull request by tivervac**
Didn't replace any occurrences in tests, also avoided a few uses where it could change behavior.

### CODE REVIEW

**Comment by tivervac** [comment]
Seems like I have some more work to do, no need to review this until the PR is stable

**Comment by szarnekow** [comment]
What is the status here?

**Comment by tivervac** [comment]
I was having issues getting jenkins to pick up my branch on xtext-core, will try to get it fixed

**Comment by tivervac** [comment]
Requires [this PR in xtext-core](https://github.com/eclipse/xtext-core/pull/966)

**Comment by tivervac** [comment]
Ouch, I forgot about this, I'll see if I can get it back up to speed

**Comment by cdietrich** [comment]
@tivervac @szarnekow what is the state of this pr

**Comment by kthoms** [comment]
rebased

**Comment by tivervac** [comment]
If the build is green this should be mergeable.
@kthoms I don't see build information, is this due to the switch to eclipse ci?

**Pull request merged**
