### PR TITLE
X2J: Migrated Xtend code from the org.eclipse.xtext.ui project to Java

### PR DESCRIPTION
**Pull request by nbhusare**
- [x] Migrated Xtend code to Java
- [x]  Ran the Maven/Gradle build locally

Signed-off-by: nbhusare <neerajbhusare@gmail.com>

### CODE REVIEW

**Comment by nbhusare** [comment]
@cdietrich In the "xtext.ui" project, we are left with two Xtend files `TemplateProcessor` and `FeatureProjectFactory`. Both make use of template. Should I migrate this code too?

**Comment by cdietrich** [comment]
I would prefer to keep The active annotations as Xtend for now.

**Comment by nbhusare** [comment]
@cdietrich Do you want me to close this PR?

**Comment by cdietrich** [comment]
i hoped @szarnekow or @ArneDeutsch would give their opinion

**Comment by szarnekow** [comment]
Sorry, this one slipped through the cracks. I'd prefer the active annotations to remain as they are.

**Comment by cdietrich** [comment]
then lets close this for now

**Pull request closed without merging**
