### PR TITLE
[527522] Avoid OperationCancelledException to be propagated

### PR DESCRIPTION
**Pull request by szarnekow**

### CODE REVIEW

**Comment by szarnekow** [comment]
A slightly different approach to https://github.com/eclipse/xtext-eclipse/pull/461

**Comment by miklossy** [comment]
The failing Quickfix test cases are not related to this change. The reason for that is described [here](https://github.com/eclipse/xtext-eclipse/pull/1000#issuecomment-469000796). [Workaround](https://github.com/eclipse/xtext-eclipse/pull/1000/commits/a0a6ef14dcd68408d92085e59db58011d7690a4b) exists in a PR, but not yet merged.

**Comment by cdietrich** [comment]
should be rebased

**Comment by cdietrich** [comment]
still need rebasing @szarnekow

**Comment by szarnekow** [comment]
> still need rebasing @szarnekow

Done

What do you think @cdietrich ?

**Comment by cdietrich** [comment]
@ArneDeutsch ?

**Comment by szarnekow** [comment]
@ArneDeutsch comment was about the failing test, which was indeed unrelated. I'm inclined to merge this PR.

**Comment by szarnekow** [comment]
Any chance to get this merged rather sooner than later?

**Pull request merged**
