### PR TITLE
[#841] Replace dependency o.e.equinox.ds by o.a.felix.scr

### PR DESCRIPTION
**Pull request by kthoms**
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by kthoms** [comment]
Tests are here: https://ci.eclipse.org/xtext/job/xtext-eclipse/job/kth_issue841/2/testReport/

**Comment by cdietrich** [comment]
They are not. Build is run with (o)
Please run with (x)
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/kth_issue841/

**Comment by kthoms** [comment]
I see. Started job https://ci.eclipse.org/xtext/job/xtext-eclipse/job/kth_issue841/
Could be that Tycho needs to set autostart for felix.scr

**Comment by cdietrich** [comment]
Yes see discussions In the bugzila(s)

**Comment by cdietrich** [comment]
same "no tests" as on typefox jenkins

**Comment by kthoms** [comment]
replaced by #860

**Pull request closed without merging**
