### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mark-christiaens**

### CODE REVIEW

**Comment by cdietrich** [comment]
thanks for the contribution @mark-christiaens 
unfortunately the eclipse foundation requires commits to be signed off and you need to have a signed Contributor Agreement.

Would you like to do that or should i simply fix the two typos on my behalf.

**Comment by mark-christiaens** [comment]
I've accepted the Eclipse contributors agreement now and force pushed a version with my sign-off.  I think that passes the IP-validation check.

**Comment by cdietrich** [comment]
yes thanks.

**Comment by kthoms** [comment]
Thank you for this contribution!

**Pull request merged**
